### ISSUE TITLE
When changing investigate => build => investigate, z-ordering should be preserved

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit#106]

**Comment by samreid** [comment]
In the above commit, I move black box elements behind the black box when switching to "build", in my testing it solves the problems we were experiencing but I'm not sure whether other unexpected behavior may result.  @arouinfar should test this after I publish a new version.

**Comment by samreid** [comment]
On hold while I work on other high-priority issues.

**Comment by samreid** [comment]
> In the above commit, I move black box elements behind the black box when switching to "build"

This may be responsible for the solder going in front.

**Comment by arouinfar** [comment]
@samreid I don't think the solder popping to the front is a blocking issue for the MVP.

**Comment by samreid** [comment]
Please see #126 for a test version.

**Comment by arouinfar** [comment]
👍
