### ISSUE TITLE
Object detaches from its vertex during rotation (Black Box screen)

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit#108]
On current master (5/19 3:00 PM). Ignore performance:

![cckbb01](https://cloud.githubusercontent.com/assets/5863899/15409798/a132d302-1dd3-11e6-93d1-b90041b0c975.gif)

**Comment by samreid** [comment]
The simplest solution seems to be to prevent rotations when there are multiple neighbors, I'll commit shortly.

**Comment by samreid** [comment]
Fixed above, will benefit from testing by @arouinfar to see if anything else was disturbed.

**Comment by arouinfar** [comment]
Seems like this issue has been fixed. I've testing this issue, but haven't done a thorough review of master @samreid.

**Comment by samreid** [comment]
Thanks @arouinfar, I'll close this issue and we can continue a thorough review of master elsewhere.
