### ISSUE TITLE
What color should inside the black box be in "build" mode?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit#109]
in #107 we discussed graying out the "investigate" wires.  While working on that I had to remove the semitransparent overlay and change it to a background color.  Then I set the inside of the black box to be blue, the same shade as where the user normally creates things:

![image](https://cloud.githubusercontent.com/assets/679486/15417660/9c06ead4-1e15-11e6-8483-fc9b1d5ca060.png)

I see the advantage of keeping this color the same as the play area, however it seemed odd for the inside of the black box to look blue so I thought I'd take a look with gray or light gray to see if it looks better (more intuitive and equally inviting).  Here is gray:
![image](https://cloud.githubusercontent.com/assets/679486/15417696/dd9a896a-1e15-11e6-8c4d-83f7dafe188f.png)

and lightgray:
![image](https://cloud.githubusercontent.com/assets/679486/15417702/eb6a6286-1e15-11e6-9452-a923269d4b70.png)

If we are going for "gray = disabled" then these may be bad options.  But I wanted to run these ideas past @arouinfar and see what she thinks.

**Comment by arouinfar** [comment]
@samreid I think the goal of matching the color of the inside of the black box to the playspace is to cue that the black box has been removed.  While gray could be interpreted as being the outline of the black box, it may also give the appearance of being disabled.

I would suggest we leave the inside of the box blue for now, and wait to see what feedback Stanford has.

**Comment by arouinfar** [comment]
Let's keep it as is.
