### ISSUE TITLE
Increase the number of wires

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit#110]
There seems to be an infinite number (or extremely large number) of batteries, bulbs, and resistors available, but a limited number of wires. I ran into a few situations where I ran out of wires under somewhat reasonable circumstances.

For example, I tried to build this setup, but I didn't have enough wires to connect two of the batteries.  The reason I used so many wires was so that I could measure the current after each component -- something a student might try do. (Students often have the idea that current is "used up" by resistors.)
![image](https://cloud.githubusercontent.com/assets/8419308/15581549/0a8f02b6-232a-11e6-85ce-6483b318260e.png)

On the Black Box screen, students can access 5 wires in Investigate mode, and 5 wires in Build mode. For more complicated black boxes this is a little restrictive. For example, I attempted to attach a battery to each corner of the black box. That way I could quickly attach and detach wires for a variety of of test cases. However, I ran out of wires too soon.
![image](https://cloud.githubusercontent.com/assets/8419308/15581996/0f5a3e6c-232c-11e6-92ad-0d644556b585.png)

I think bumping the number of wires up to 16 would allow a situation like the ones above, while still being somewhat restrictive.

@samreid do you have any thoughts about the number of wires we should allow? I was thinking something in the 15-20 range.

**Comment by arouinfar** [comment]
No need to take care of this before our meeting with Stanford tomorrow, but it should be addressed for the version that will be used with students.

**Comment by arouinfar** [comment]
@samreid this issue should be addressed while making the other changes for Stanford.

**Comment by samreid** [comment]
It looks like there can be 10 wires, but it is counting the wires inside the black box toward the total.

**Comment by samreid** [comment]
Fixed in the above 2 commits.

**Comment by samreid** [comment]
Please refer to #126 for a test version.

**Comment by arouinfar** [comment]
👍
