### ISSUE TITLE
Add "What circuit is in the black box?" text to Warm-Up; Disable during Reveal

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit#111]
In #30 I requested that the "What circuit is in the black box?" text be killed while "Reveal" is being pressed. I thought it may potentially confuse students to ask them what is in the black box while simultaneously revealing its contents.

However, I just realized that the text is now completely absent from the Warm-Up during Investigate mode. The prompt is a critical part of cueing the "game" to students. 

@samreid please add this text back to the Warm-Up black box while in Investigate mode, but disable it while "Reveal" is pressed.

If this is a quick fix, can this be done in time to push a new dev version before we meet with Stanford this afternoon?

**Comment by samreid** [comment]
My mistake, I misinterpreted https://github.com/phetsims/circuit-construction-kit/issues/30#issuecomment-216316561

I'll work on this now.

**Comment by samreid** [comment]
Fix published here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box/1.0.0-dev.14/circuit-construction-kit-black-box_en.html

@arouinfar can you please test the feature change and try making a few explore circuits and black box circuits to make sure nothing was disturbed?

**Comment by arouinfar** [comment]
I completely understand why you interpreted my comment that way @samreid. Re-reading it I realized that it wasn't clear enough. 

Thanks for getting a new dev version published so quickly! Things seem to be looking good, so I'll go ahead and close this issue.
