### ISSUE TITLE
Add a query parameter that adds a play/pause button for Black Box

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit#112]
An option to show play/pause button.  Query parameter.
Add a play/pause button.  When manipulating circuit, it goes to pause.
When play, it shows the meter values.  Grayed out box for the text like the meter is turned off.
Suppress light bulb values as well.

**Comment by samreid** [comment]
Having a play/pause button toggles back and forth between play/pause may be very confusing.  If it looks like "pause" it means it is playing.  Usually this is not too much of a problem in other sims because there are other moving parts, but since this only toggles whether values and bulb brightness are displayed it could be extra confusing.

**Comment by samreid** [comment]
Another reason I think the "play/pause" analogy is faulty: if a light bulb shines then is paused, it normally wouldn't stop shining.  Perhaps a reveal/hide button (eyeball icon?) would be more intuitive?

**Comment by samreid** [comment]
The next concern is that we would like the "zero-current" light bulb to look different from the "paused" light bulb.

**Comment by samreid** [comment]
Using the transparency could conflict with the transparency used in #107.

**Comment by samreid** [comment]
Working with the light bulb will be easier once we have a custom node for CCK.  Other than that, this issue is ready to review.

**Comment by arouinfar** [comment]
> Having a play/pause button that toggles back and forth between play/pause may be very confusing. If it looks like "pause" it means it is playing.

> Another reason I think the "play/pause" analogy is faulty: if a light bulb shines then is paused, it normally wouldn't stop shining. Perhaps a reveal/hide button (eyeball icon?) would be more intuitive?

I also find the play/pause buttons a bit problematic. I like your suggestion to use the reveal icon @samreid, but I don't think it's necessary to have text on these buttons. While in "pause" mode, the eyeball button would be showing. While in "play" mode, the button could show an eyeball with a strikethrough. FontAwesome has icons for both situations.
![image](https://cloud.githubusercontent.com/assets/8419308/15639163/181f1850-25ee-11e6-9c7f-a80d870bc579.png)

> The next concern is that we would like the "zero-current" light bulb to look different from the "paused" light bulb.

We had discussed layering a gray shape over the light bulb to make the bulb look less bulb-like (i.e. hide the filament) while in pause mode. However, we decided this was an unnecessary feature. The bulb artwork will not be altered in "pause" mode, aside from suppressing the rays @samreid.

I've created issue #118 for the lightbulb artwork.

**Comment by samreid** [comment]
I'm somewhat concerned that putting the icon on the button will still have the opportunity for confusion.  For instance, if the open eye is showing in "pause" mode as described above, some may attribute it to meaning "If I press this button, then it will be in open eye mode", because this is the normal way that play/pause buttons work in video controllers.  So I've hedged my bets and left the triangle bars button and put an icon above like so:

![image](https://cloud.githubusercontent.com/assets/679486/15687531/861f41c8-2732-11e6-949c-17d571808ac6.png)

The icon on the button shows what will happen if you press the button.  The icon above the button shows the current status.  I'd like to post a version for @arouinfar to review but first I'd like to address this request:

> When manipulating circuit, it goes to pause.

**Comment by samreid** [comment]
In the preceding commit, when the user manipulates the circuit, the readouts are hidden.  This is ready for review in the next version.

**Comment by samreid** [comment]
The query parameter is ?showPlayPauseButton

Please see https://github.com/phetsims/circuit-construction-kit/issues/126 for test version.

**Comment by arouinfar** [comment]
I find the combination of the play/hide and pause/reveal icons highly confusing. If I press "play" is it going to play something, or is it going to hide something? 
![image](https://cloud.githubusercontent.com/assets/8419308/15912659/dddc2ea6-2d92-11e6-9f51-115d9ce55c2a.png)  ![image](https://cloud.githubusercontent.com/assets/8419308/15912669/f5b6dbc0-2d92-11e6-8b01-25a609e9ddfa.png)

The play/pause alone does have a drawback -- the sim is paused while the button shows a play symbol. However, play/pause buttons are ubiquitous, and after it's pressed once, the functionality will become clear. I find it much clearer to interpret a single play/pause button. Having an icon that tells me which state I'm currently in (show/hide) while simultaneously showing a button that will change my state (pause/play) is very confusing to me. 

The play/pause functionality seems a bit too sensitive, as well, but I'll open up a separate issue.

@samreid can you remove the show/hide eyeball icon and leave it as just a play/pause button?

**Comment by samreid** [comment]
I removed the eyeball icons from above the play pause button, this will be ready for review in the next version.

**Comment by samreid** [comment]
Please see #134 for testing.

**Comment by arouinfar** [comment]
👍
