### ISSUE TITLE
When deleting a wire, other connected vertices disconnect (they shouldn't)

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit#115]
When deleting a wire, other connected vertices disconnect (they shouldn't)

**Comment by arouinfar** [comment]
More generally, when deleting a component connected to a node with 3+ connections, the other components should remain connected. The deleted component doesn't necessarily need to be a wire.

**Comment by samreid** [comment]
Fixed above, this is a significant model change and will need testing.

**Comment by samreid** [comment]
Please see #126 for testing.

**Comment by arouinfar** [comment]
This appears to be working nicely in dev.15. Closing.
