### ISSUE TITLE
Fixes for when one circuit element dropped directly on top of another

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit#117]
When one circuit element dropped directly on top of another, connect one vertex and move the other vertex.  Should be done for wires too.

**Comment by arouinfar** [comment]
👍 

Additionally, components should not snap on top of one another.

**Comment by samreid** [comment]
The solution I was envisioning is actually more complex than I anticipated, because we may need to search out a group of components from a pivot vertex and rotate the entire group around the point.

**Comment by samreid** [comment]
Though rotating a subgroup about a vertex could come in handy elsewhere, such as rotating a group about a black box vertex.  Though perhaps it would be prudent to start with a less complex solution for the simplest case (no group of connected components).

**Comment by samreid** [comment]
Initial work in https://github.com/phetsims/circuit-construction-kit/commit/016f37765b887b51d1ba3e0c58ef99cd14f39605

**Comment by samreid** [comment]
After the commits above, the functionality seems to be in a good position.  Next I'll do broader testing then publish a version for @arouinfar to take a closer look at.

**Comment by samreid** [comment]
I fixed one new bug, and am seeing other problems related to the black box vertices--we'll have to tell them (a) it is always OK to attach to them despite other rules against it and (b) never to move them even if the postprocess step wants to.

**Comment by samreid** [comment]
More fixes above, no new issues found during testing.  I'll close this one and create a new issue for broader developer testing before sharing to @arouinfar.
