### ISSUE TITLE
Very difficult to compare the transparent "disabled" light bulb to the enabled one

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit#124]
From #122, it is very difficult to compare the light bulb brightness between build and investigate:

Investigate:
![image](https://cloud.githubusercontent.com/assets/679486/15779512/0ba4f616-295a-11e6-80c2-ed7509e976c8.png)

Build:
![image](https://cloud.githubusercontent.com/assets/679486/15779517/15aec0a6-295a-11e6-8750-011c1bef52d8.png)

Should make the light bulb fully opaque in either case so that you can visually compare the light bulb?  Alternatively, we could make the light bulb image transparent but leave the brightness lines fully opaque?

Assigning to @arouinfar for discussion.

**Comment by arouinfar** [comment]
@samreid let's try leaving the bulb image transparent, while giving the light rays full opacity.

**Comment by samreid** [comment]
Fixed above, closing.
