### ISSUE TITLE
Deleting components can delete vertices from the black box

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit#129]
Black box vertices can be deleted while building a circuit. They will return upon most sim state changes, however. This will happen when deleting an object from such a vertex, only in Build mode and only if nothing else is attached to the vertex. The vertex on the right will be deleted since nothing else is attached to it, the vertex on the right will remain because the battery is attached:

![cckbb03](https://cloud.githubusercontent.com/assets/5863899/15836723/5bb5e8d6-2bf3-11e6-9f46-a901206382a6.gif)

For #126.

**Comment by samreid** [comment]
Fixed above, will need to be tested.  This bug may have been introduced by another "fix" so we should be vigilant to try to identify if this causes a correlated bug.

**Comment by samreid** [comment]
Published in https://github.com/phetsims/circuit-construction-kit/issues/134 for testing.

**Comment by arouinfar** [comment]
This appears to be fixed, but I'd like to keep this one open for @phet-steele to take a look at when he works on #134.

**Comment by phet-steele** [comment]
@samreid I don't see this anymore.
