### ISSUE TITLE
Play/pause too sensitive

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit#130]
Discovered as part of #126.

The play/pause button is too sensitive. Currently, if any circuit component is moved while the circuit remains connected and otherwise unchanged, the sim will kick itself into pause mode. 

![playpause](https://cloud.githubusercontent.com/assets/8419308/15912937/96462018-2d94-11e6-844a-1dde719de443.gif)

The sim should pause automatically if:
* More components are dragged out of the toolbox
* Any vertex is broken
* Component voltage/resistance is edited. (I'm on the fence about this one, but changing these values does change the circuit...)

The sim should stay in play mode if:
* Any vertex is dragged, but not severed
* Component is dragged, but not changed

(These behaviors are exemplified in the .gif above)

**Comment by samreid** [comment]
When a wire's length changes, its resistance changes.  Should we make this change in resistance a special case that doesn't trigger pause mode?

**Comment by arouinfar** [comment]
Ah, makes sense @samreid.  Yes, let's make the change in resistance due to the change in a wire's length a special case that doesn't trigger pause.

**Comment by samreid** [comment]
Making it so that the system can detect whether the NumberControl/HSlider changed the property value seems like it would be very difficult, and could involve changes to those sun classes.  If I could easily make a property proxy, that might work but it could be brittle (would have to support entire Property API) with delegates for potentially every method.

**Comment by samreid** [comment]
Fixed above using a proxy Property, will need to be thoroughly tested.

**Comment by samreid** [comment]
Please test in https://github.com/phetsims/circuit-construction-kit/issues/134

**Comment by arouinfar** [comment]
Looks good!
