### ISSUE TITLE
Node highlight code is fragile

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit#133]
> In the above commit, the endVertex is set to an angle of zero, then the layout is performed, then the endVertex position is restored. The behavior seems to be correct, however we must understand why this behavior is occurring and find a better solution.

From #102 

I've marked this for the study version since it seems possible that the workaround could result in buggy/quirky behavior for connected chains of circuit elements.

**Comment by samreid** [comment]
Fixed above, should be reviewed in next version since it affected the way all highlights are drawn.

**Comment by samreid** [comment]
Please test in https://github.com/phetsims/circuit-construction-kit/issues/134

**Comment by arouinfar** [comment]
@samreid I was not able to reproduce the issue described in #102 using @phet-steele's method in dev.16. I haven't encountered any instance of the node highlight misbehaving, but I think this is an issue that @phet-steele should bang away at when I pass #134 off to him.  (@phet-steele -- I'll create a QA testing issue in tasks when the time comes.)

**Comment by samreid** [comment]
Putting on hold until a new version is published.

**Comment by samreid** [comment]
Please refer to https://github.com/phetsims/circuit-construction-kit/issues/140 for testing.

**Comment by phet-steele** [comment]
@samreid I can't reproduce with my old procedure either, I'll deem as fixed for now.
