### ISSUE TITLE
Voltmeter has backwards reading

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/circuit-construction-kit#135]
For phetsims/tasks#617

Test device: Dirac

Operating System: 10.10.5

Browser: Safari

Problem description: The voltmeter reads battery voltages backwards, giving the negative value of what it should be. (Confirmed by @arouinfar that this is actually wrong and I'm not just remembering incorrectly about how it should work.)

Screenshots:
![cck](https://cloud.githubusercontent.com/assets/11947677/16132646/4c0a4068-33d1-11e6-9843-7c421ada5b78.png)

Troubleshooting information (do not edit):
Name: ‪Circuit Construction Kit: Black Box‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box/1.0.0-dev.16/circuit-construction-kit-black-box_en.html
Version: 1.0.0-dev.16 2016-06-14 05:55:02 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7
Language: en-us
Window: 1054x604
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-10.0.35)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"b71cc337","branch":"master"},"babel":{"sha":"234b6178","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"4c679115","branch":"master"},"circuit-construction-kit":{"sha":"c97a71ee","branch":"master"},"circuit-construction-kit-black-box":{"sha":"a7a4d38e","branch":"master"},"dot":{"sha":"455447ce","branch":"master"},"joist":{"sha":"ddf0d912","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"d2791b0f","branch":"master"},"scenery-phet":{"sha":"822e3d6d","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"sun":{"sha":"f2631eea","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"}}

**Comment by arouinfar** [comment]
Good catch @brroberts1231. Also tagging #134.

For comparison here's the Java version CCK and Capacitor Lab: Basics
![image](https://cloud.githubusercontent.com/assets/8419308/16132898/77b670be-33d2-11e6-9114-47a8eb73731e.png) ![image](https://cloud.githubusercontent.com/assets/8419308/16132920/880a1de4-33d2-11e6-81e4-083732cc12b9.png)

If the red (positive) probe is on the positive terminal of the battery, the voltage reading should be positive.

**Comment by samreid** [comment]
This may have broken in https://github.com/phetsims/circuit-construction-kit/issues/101

**Comment by samreid** [comment]
Hence we may solve this by turning around the battery image and reversing the flow of electrons.

**Comment by samreid** [comment]
OK the battery is forward again and things are looking good.  
![image](https://cloud.githubusercontent.com/assets/679486/16157401/a32b3f42-3475-11e6-9172-d117ca405fc5.png)

I'll have to reopen #101 and solve it a different way.

**Comment by samreid** [comment]
Please refer to https://github.com/phetsims/circuit-construction-kit/issues/140 for testing.

**Comment by phet-steele** [comment]
@arouinfar @samreid I can verify that voltages are read correctly in 1.0.0-dev.17

**Comment by samreid** [comment]
Thanks @phet-steele, closing.
