### ISSUE TITLE
Clicking components can sometimes create a connection with another nearby component

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit#142]
@samreid here's one way to reproduce, this isn't exactly consistent. This way detaches the battery from its positive vertex.

![cckbb06](https://cloud.githubusercontent.com/assets/5863899/16211049/7a69513c-36fc-11e6-8e4f-6efcf4e6bc12.gif)

For phetsims/tasks/issues/617.
Troubleshooting information:
Name: ‪Circuit Construction Kit: Black Box‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box/1.0.0-dev.17/circuit-construction-kit-black-box_en.html
Version: 1.0.0-dev.17 2016-06-20 19:15:41 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
Language: en-US
Window: 1622x1002
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"b71cc337","branch":"master"},"babel":{"sha":"047295f6","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"e044eccd","branch":"master"},"circuit-construction-kit":{"sha":"34780a85","branch":"master"},"circuit-construction-kit-black-box":{"sha":"88cbfaf4","branch":"master"},"dot":{"sha":"551f726f","branch":"master"},"joist":{"sha":"a42bced7","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"4476eb95","branch":"master"},"scenery-phet":{"sha":"52b783d9","branch":"master"},"sherpa":{"sha":"77506dc3","branch":"master"},"sun":{"sha":"0d7e743b","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"}}

**Comment by samreid** [comment]
Backlinking to https://github.com/phetsims/circuit-construction-kit/issues/140

**Comment by samreid** [comment]
I'm getting a "vertex wasn't in the model" error that is preventing me from investigating further...

**Comment by samreid** [comment]
@phet-steele pointed out #119 also has a "vertex wasn't in the model error".  I suspect it is the same symptom from a different root cause.

**Comment by samreid** [comment]
Fixed the "vertex wasn't in the model" error and after several minutes of tinkering, am unable to reproduce the problem from the issue description.  Perhaps it has been fixed (optimistic) or perhaps I was unlucky and didn't stumble across the issue (pessimistic).

**Comment by samreid** [comment]
@phet-steele are you available to pull latest on phettest and see if the problem from the issue description can be reproduced?

**Comment by phet-steele** [comment]
@samreid I still made it work as shown above

**Comment by samreid** [comment]
Thanks, I tried again and was successful.  Here's a surefire way to reproduce the problem:

![snap](https://cloud.githubusercontent.com/assets/679486/16597036/0ef145e0-42b4-11e6-9934-88bcc87c5460.gif)

**Comment by samreid** [comment]
I can work around the problem by only calling endDrag if drag was called.  This works correctly but leads to an asymmetry in the code and perhaps we should investigate why the buggy behavior is appearing in the first place.

**Comment by samreid** [comment]
The logic assumes that a vertex has been moved to a proposed connection position before endDrag is called.  The two possible solutions for this are (a) to call drag on startDrag, so the vertex will jump immediately or (b) to avoid connections when only a click has happened, this would be implemented as described in the preceding comment.  I guess it makes most sense that the user should have to move a vertex at least 1 pixel before we infer that they want to connect it to something, so I'll go with (b).

**Comment by samreid** [comment]
OK fixed above, now an object has to be moved (and matches proposed) before connections can be made.  Now I'm seeing a behavior where a vertex is moved out of the way if things are put close but not connecting, but that seems desirable so far (though there may be some buggy corner cases).
