### ISSUE TITLE
This repo is considered "common" on phettest

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit#43]
@samreid @jonathanolson this repo, CCKB, has been appearing on phettest as a common repo for some time now. See in the screenshot below CCKB is reffered to as a common repo in the red text on the top, and is not included in the list of sims. Check for yourselves on http://phettest.colorado.edu while using a VPN.
![cckcommon](https://cloud.githubusercontent.com/assets/5863899/14088391/71e5a1b6-f4ec-11e5-9f35-258ad373d4b1.PNG)

**Comment by samreid** [comment]
It looks like adding circuit-construction-kit-basics (in the above commit) has resolved the issue:

![image](https://cloud.githubusercontent.com/assets/679486/14098208/b58348ca-f536-11e5-800b-6a7c445dd419.png)

**Comment by phet-steele** [comment]
@samreid hate to ask, but can you do this again? The renaming of this repo is to blame :smile:, so CCK needs to be put into active-sims.

**Comment by samreid** [comment]
I'm confused about how phettest.colorado.edu deals with common repos.

At the top I see
![image](https://cloud.githubusercontent.com/assets/679486/15098955/218e536c-1507-11e6-8a07-4062190e197b.png)

in the sims I see:
![image](https://cloud.githubusercontent.com/assets/679486/15098956/2a18f8a2-1507-11e6-946d-0e0489247a5b.png)

As of writing, active-repos has:
![image](https://cloud.githubusercontent.com/assets/679486/15098959/3af87828-1507-11e6-8d28-c8f4d1934b96.png)

Active-runnables has:
![image](https://cloud.githubusercontent.com/assets/679486/15098962/4261950e-1507-11e6-8650-e6da13a904b2.png)

Active-sims has:
![image](https://cloud.githubusercontent.com/assets/679486/15098967/4a60c0d6-1507-11e6-889d-06c2ebd3ec78.png)

circuit-construction-kit-basics and circuit-construction-kit-black-box are sims, circuit-construction-kit is now a shared sim repo that does not currently have a sim (in the future it will have the "Circuit Construction Kit" (non-basics) sim.

@phet-steele can you please advise?

**Comment by phet-steele** [comment]
@samreid all is well.
