### ISSUE TITLE
Rotate components attached to an unmovable vertex

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit#67]
Currently a fixed length circuit element cannot be rotated when it is anchored to an unmovable vertex.

This is probably not be necessary for MVP.

![image](https://cloud.githubusercontent.com/assets/679486/14685379/9d6d79b4-06f1-11e6-81d0-816a0a27e396.png)

**Comment by samreid** [comment]
After investigating this, it seems like it could be more than 2 hours to implement (and more if we try to handle the arbitrary case of other components connected to the black box vertex).  So I'd rather check about how important it is before spending time.  @arouinfar what do you think?

**Comment by arouinfar** [comment]
This is definitely not important for the MVP @samreid, but it would be good to fix for future iterations.

**Comment by arouinfar** [comment]
@samreid Originally I thought about this issue as it relates to attaching external components to the black box. However, this issue makes it a bit tricky to make more advanced black boxes, like the one below.

<img width="315" alt="screen shot 2016-05-02 at 11 42 49 pm" src="https://cloud.githubusercontent.com/assets/8419308/14964930/cd691646-10bf-11e6-9a47-8d787e81bdfc.png"><img width="300" alt="screen shot 2016-05-02 at 11 42 53 pm" src="https://cloud.githubusercontent.com/assets/8419308/14964931/cd6e7e06-10bf-11e6-802e-e54f219cf02a.png">

This issue has the potential to cause problems during the study. Students may have a hard time coordinating across these different representations.

@ariel-phet can you take a look at this issue and comment?

**Comment by ariel-phet** [comment]
@arouinfar @samreid 

I would say this is quite important for the "build" mode

I see two options:

1. implement the ability to rotate when attached to a fixed vertex

2. give the black box internal "wire stubs" at each vertex, this seems to fix the issue (as shown below)

![cck](https://cloud.githubusercontent.com/assets/4051174/14969965/a56f8a68-1082-11e6-801e-23bb231b2134.PNG)

Back to you @arouinfar (I am guessing the wire stub solution would work for the MVP), and likely easy for @samreid to implement

**Comment by samreid** [comment]
I expect adding rotation for components connected to the black box vertices would be simpler than adding wire stubs, I'll assign to myself for implementation but @arouinfar please weigh in if you have other thoughts or suggestions.

**Comment by arouinfar** [comment]
Thanks @ariel-phet, and I like your suggestion. However, please feel free to take the whatever approach you find the simplest @samreid.

**Comment by samreid** [comment]
In the above commit you can rotate a component when it is only connected to a black box vertex.  It would be more work to make it rotateable when it is also attached to other things.

**Comment by samreid** [comment]
Fixed above, will need testing in next version.

**Comment by arouinfar** [comment]
It's looking good @samreid! I didn't run into any issues during #85.

**Comment by samreid** [comment]
Excellent, thanks!  #86 may be related but we can close this issue and follow up with related issues.
