### ISSUE TITLE
Text in meters moves with large strings

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit#84]
Observed in dev.10. Should be fixed before Stanford can use it with students.

If a large string is encountered, the meter label and readout window will shift to the left. Repeating a measurement with a large string will continue to move the text. To fix the issue, the browser needs to be refreshed. Reset all does fix the issue.

![currentmeter](https://cloud.githubusercontent.com/assets/8419308/14964408/3d49f64a-10bd-11e6-91f5-2629567416e4.gif)

![voltmeter](https://cloud.githubusercontent.com/assets/8419308/14964605/2de1849c-10be-11e6-9fb2-f995d7ae9528.gif)

**Comment by samreid** [comment]
Putting a max width on this text works nicely:
![image](https://cloud.githubusercontent.com/assets/679486/15084954/38e8eb5e-1394-11e6-8f96-6ed294cf70c1.png)

**Comment by samreid** [comment]
Max width committed above, closing.

**Comment by arouinfar** [comment]
@samreid I reviewed this issue for #85, and it looks good for the MVP. My only suggestion would be to vertically center the text within the window.

**Comment by samreid** [comment]
> @samreid I reviewed this issue for #85, and it looks good for the MVP. My only suggestion would be to vertically center the text within the window.

OK I'll create a new issue for that.
