### ISSUE TITLE
Test a version for Stanford

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit#85]
In #82 I posted a version of Black Box for design team testing.  I've fixed issues #30, #84 and #67 and all other reported issues are "not for MVP", so we can create a MVP release candidate.  I'll publish a version, take it for a test drive on a few platforms and if I don't see any blocking issues I'll request broader testing from the CCK Black Box team.  If all goes well, we could deliver that version to Stanford for feedback.

**Comment by samreid** [comment]
Published here, I'll test a few browsers before I request help from the rest of my team:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box/1.0.0-dev.11/circuit-construction-kit-black-box_en.html

**Comment by samreid** [comment]
Two problems identified above, nothing else severe noted on Firefox, Safari or Chrome.  @arouinfar can you take a look and verify that the changes in #30, #84 and #67 look ok, review #86 and #87 to see if you can reproduce them and think they must be solved before sharing a version with Stanford, and see if anything else should be done before sharing first version with Stanford?

**Comment by arouinfar** [comment]
Everything looks good on my machine (latest Mac/Chrome) @samreid!  I think dev.11 is ready to share with Stanford.

**Comment by samreid** [comment]
@arouinfar would you like to share dev.11 to our contacts at Stanford?

**Comment by samreid** [comment]
Today we agreed that @phet-steele should test dev.11 before we share it to Stanford.  @phet-steele can you test dev.11 on a few desktop browsers and let us know if you spot any user interface or physics issues?

**Comment by phet-steele** [comment]
@samreid suggested to stop testing due to the sim killing errors in #102. Unassigning.

**Comment by arouinfar** [comment]
Thanks for banging away at this @phet-steele. I'm clearly not as devious as you are.

@samreid I haven't shared dev.11 with Stanford, and it looks like we may still want to wait awhile.

**Comment by ariel-phet** [comment]
@arouinfar yes...lets make sure the version we share is reasonably bug free

**Comment by samreid** [comment]
After I clean up the new code created during porting of the electrons and switches, I'll give a new version to @phet-steele to test.

**Comment by samreid** [comment]
Code is cleaned up and in #102 I recommended to use master on test-server for testing, so we can get more helpful error messages from the console.  @phet-steele good luck and let me know what you find!

**Comment by samreid** [comment]
See #102

**Comment by samreid** [comment]
After fixing all other "high-priority" issues in this repo, @arouinfar will test the sim and if all appears well we will deliver it to Stanford, hopefully within a week or so.

**Comment by samreid** [comment]
Delivered initial version to Stanford, closing.
