### ISSUE TITLE
Light bulb gets into an odd situation

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit#86]
Discovered in #85, sometimes the light bulb gets into an odd situation:
![image](https://cloud.githubusercontent.com/assets/679486/15101881/12e8e8c8-1556-11e6-9249-23c83c22c445.png)

**Comment by samreid** [comment]
It's not clear from the pic, but the battery and light bulb are connected (and a connection point from the bulb is missing).

**Comment by arouinfar** [comment]
@samreid while playing around with the latest dev in OSX 10.11.4/Chrome 50, I wasn't able to reproduce this issue.

**Comment by samreid** [comment]
I think this was caused by #103, I'll close this and continue in that issue.
