### ISSUE TITLE
Ammeter/voltmeter does not read values from inside the black box during "reveal"

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit#87]
During #85, I was comparing my circuit to the black box circuit using "reveal" and realized that we have programmed the probes to not read values from inside the black box--this also applies while the black box is in the partially-transparent "reveal" mode.  @arouinfar can you recommend how to proceed?

**Comment by arouinfar** [comment]
Are you referring to a situation like this @samreid?
![voltage_reading](https://cloud.githubusercontent.com/assets/8419308/15113596/7764e036-160a-11e6-8366-3b9a345945c5.gif)

If so, I think it would be nice if the voltmeter would continue to read while the contents of the black box are revealed. Though in this situation, the student could move the probes to the terminals of the box to get the reading.

I don't think it's necessary to address this issue for the MVP. However, if it's a quick fix, I think it's worth doing.

**Comment by arouinfar** [comment]
"Quick" meaning 30 minutes or less. I don't think this issue should block dev.11 from being shared with Stanford.

**Comment by samreid** [comment]
Yes, that's the problem I was referring to.  I'll investigate to see whether this would be easy or tricky.

**Comment by samreid** [comment]
CircuitConstructionKitScreenView.js has this method:

```js
    hitWireNode: function( probeNode, locationProperty ) {
      for ( var i = 0; i < this.circuitNode.wireNodes.length; i++ ) {
        var wireNode = this.circuitNode.wireNodes[ i ];

        // Don't connect to wires in the black box
        if ( !wireNode.wire.insideTrueBlackBox && wireNode.getStrokedShape().containsPoint( probeNode[ locationProperty ] ) ) {
          return wireNode;
        }
      }
      return null;
    }
```

If we change the logic here, we would also need to trigger this method to be called again when the black box contents are revealed.

**Comment by samreid** [comment]
Fixed above, will be ready for review in next version.

**Comment by samreid** [comment]
Please see #134 for testing.

**Comment by arouinfar** [comment]
@samreid it looks like things are not quite working. Here's a screencast showing one case that doesn't work (Warm-Up) and one that does (Black Box 2). In the Warm-Up, the resistor in "Reveal" shows an undefined voltage, even when the probes are moved around.

![probeinblackbox](https://cloud.githubusercontent.com/assets/8419308/16052977/fcdf0d24-3223-11e6-90cd-32dccc277f6e.gif)

**Comment by arouinfar** [comment]
Here's another example
![probeinblackbox2](https://cloud.githubusercontent.com/assets/8419308/16053117/aa5fddfc-3224-11e6-845b-e48ee21f04b7.gif)

**Comment by samreid** [comment]
I reproduced the problem, thanks @arouinfar!

**Comment by samreid** [comment]
There was another place that needed to get new logic about reveal mode, should be fixed above.  Putting on hold until I publish another version for @arouinfar to test.

**Comment by samreid** [comment]
Please refer to https://github.com/phetsims/circuit-construction-kit/issues/140 for testing.

**Comment by phet-steele** [comment]
@samreid @arouinfar I haven't seen it not read during reveal in 1.0.0-dev.17

**Comment by samreid** [comment]
Thanks @phet-steele, I'll close the issue for now.
