### ISSUE TITLE
Indent "conventional current" checkbox?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit#91]
The design doc shows this control panel:
![image](https://cloud.githubusercontent.com/assets/679486/15128117/2a45602c-15f7-11e6-85b7-9eedfab67946.png)

Should we indent the "conventional current" checkbox to indicate that it is a sub-setting of "show electrons"?  Do our users pick up on this kind of indenting in interviews?

My concern is that the "conventional current" checkbox provides no visual feedback unless "Show Electrons" is checked and electrons are moving.

**Comment by arouinfar** [comment]
Good question @samreid. I think a more important question would be to ask what the conventional current looks like. This hasn't been discussed at all beyond deciding that the conventional current should somehow be displayed. (I believe this was a pretty frequent teacher request.)

I can think of a few ways we could show the conventional current
* An arrow showing the direction of the conventional current
* Positive charges flowing out from the positive terminal of the battery to the negative terminal of the battery.

If we use an arrow to represent the conventional current, it could be simultaneously shown with the electron flow. If we use the latter representation, the conventional current and show electrons would need to be mutually exclusive options (radio buttons). 

Either way, I don't think the conventional current checkbox needs to be indented. I'll tag for discussion at the next design meeting.

**Comment by samreid** [comment]
I've moved the "What should the conventional current look like" to a new issue.  I'll close this issue for now.
