### ISSUE TITLE
Should we show both directions of batteries in "Black Box"?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit#97]
Changes in "Basics" have granted "Black Box" a left-facing battery.  I was about to remove it when I realized it could be very convenient to have a left-facing battery in Black Box.  @arouinfar what do you think?

![image](https://cloud.githubusercontent.com/assets/679486/15186431/3c07744e-175a-11e6-9f73-02901e41b64d.png)

**Comment by arouinfar** [comment]
@samreid the reason for including two oppositely-directed batteries in CCK: Basics was for scaffolding purposes on the first screen. I don't think it's necessary for CCK: Black Box, but I can see that it could be a handy feature. I'd say leave the second battery in for now, with the understanding that Stanford may request for it to be removed.

**Comment by samreid** [comment]
Sounds good, we can reopen if Stanford wants it removed, closing.

**Comment by arouinfar** [comment]
Decided to go with one battery. Reopening.

**Comment by samreid** [comment]
This has been fixed, will be available for confirmation in next version.

**Comment by samreid** [comment]
Please see #134 for testing.

**Comment by arouinfar** [comment]
👍
